version: '3.7'

services:
  mysql:
    container_name: wiggli_challenge_mysql
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: wiggli_challenge
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER:     root
      MYSQL_PASSWORD: root

  php:
    container_name: wiggli_challenge_php
    build: docker/php
    ports:
      - "9000:9000"
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/conf.ini"
      - "./src/:/var/www/"

  nginx:
    container_name: wiggli_challenge_nginx
    build: docker/nginx
    ports:
      - "8007:80"
    volumes:
      - "./src/:/var/www/"
      - "./docker/nginx/logs/:/var/log/nginx"
    links:
      - php